# Generated by Django 4.2.3 on 2023-08-10 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authorUser',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='ratingAuthor',
            new_name='rating_author',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nameCat',
            new_name='name_cat',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentPost',
            new_name='comment_post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentUser',
            new_name='comment_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='dateComment',
            new_name='date_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='textComment',
            new_name='text_comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='authorPost',
            new_name='author_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categoryType',
            new_name='category_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datePost',
            new_name='date_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='postCategory',
            new_name='post_category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='textPost',
            new_name='text_post',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoryThrough',
            new_name='category_through',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='postThrough',
            new_name='post_through',
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='news.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
